[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
xess_claim = "AKRLZssgxwQwC2gGgUtYtcU7JrhDyEfk1FHqQkZnFUax"

[programs.localnet]
xess_claim = "AKRLZssgxwQwC2gGgUtYtcU7JrhDyEfk1FHqQkZnFUax"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-id.json"

[scripts]
test = "pnpm exec mocha -t 1000000 tests/"
